version: '3'

services:
  frontend:
    build: ui
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
  backend:
    build: services
    ports:
      - 5000:5000
    volumes:
      - ./storage:/storage